# Generated by Django 3.0.2 on 2020-09-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gprod_name', models.CharField(max_length=20)),
                ('gprod_desc', models.CharField(max_length=500)),
                ('gprod_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_desc', models.CharField(max_length=500)),
                ('prod_color', models.CharField(max_length=10)),
                ('prod_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vid_title', models.CharField(max_length=20)),
                ('vid_link', models.CharField(max_length=200)),
            ],
        ),
    ]
