# Generated by Django 3.0.2 on 2020-09-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0003_auto_20200921_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_color',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
