# Generated by Django 3.0.2 on 2020-09-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0004_auto_20200921_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
