# Generated by Django 3.0.2 on 2020-09-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0005_auto_20200921_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
