# Generated by Django 3.0.2 on 2020-09-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0006_auto_20200921_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Vid_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid_link',
            field=models.CharField(max_length=500),
        ),
    ]
