# Generated by Django 3.0.2 on 2020-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0007_auto_20200921_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamingproduct',
            name='gprod_desc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='gamingproduct',
            name='gprod_name',
            field=models.CharField(max_length=50),
        ),
    ]
