# Generated by Django 3.0.2 on 2020-09-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0009_remove_gamingproduct_gprod_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamingproduct',
            name='gprod_cat',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
