# Generated by Django 3.0.2 on 2020-09-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0010_gamingproduct_gprod_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamingproduct',
            name='gprod_link',
        ),
        migrations.AddField(
            model_name='gamingproduct',
            name='gprod_link1',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gamingproduct',
            name='gprod_link2',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gamingproduct',
            name='gprod_store1',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamingproduct',
            name='gprod_store2',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
