# Generated by Django 3.0.2 on 2020-09-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0011_auto_20200922_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamingproduct',
            old_name='gprod_link1',
            new_name='gprod_link',
        ),
        migrations.RenameField(
            model_name='gamingproduct',
            old_name='gprod_store1',
            new_name='gprod_store',
        ),
        migrations.RemoveField(
            model_name='gamingproduct',
            name='gprod_link2',
        ),
        migrations.RemoveField(
            model_name='gamingproduct',
            name='gprod_store2',
        ),
    ]
